### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by leichunfeng** [thedillonb/GitHub-Trending#4]
```
[root GitHub-Trending]# npm start

> codehub-trending@1.0.0 start /GitHub-Trending
> node ./bin/www


/GitHub-Trending/routes/index.js:8
  return (req, res, next) => co(fn(req, res, next)).catch(err => next(err));
                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/GitHub-Trending/app.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 2.6.32-042stab116.2
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! codehub-trending@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the codehub-trending@1.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the codehub-trending package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs codehub-trending
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls codehub-trending
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /GitHub-Trending/npm-debug.log

Exit code: 1
```

What is the problem?

**Comment by thedillonb** [comment]
You're trying to start the application up with node version 0.10.46 which is beyond old. Grab the latest, stable, build of node - 6.9.4 is current LTS.
